version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test -- --coverage
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run semantic-release

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
